-- Transactional outbox events and fenced, idempotent side-effect receipts.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS platform_outbox_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_key VARCHAR(160) NOT NULL,
    source_change_key VARCHAR(160) NULL,
    business_transaction_key VARCHAR(160) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    event_type VARCHAR(96) NOT NULL,
    payload_json LONGTEXT NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    status ENUM('pending', 'processing', 'dispatched', 'failed', 'recovery_required') NOT NULL DEFAULT 'pending',
    requires_side_effect TINYINT(1) NOT NULL DEFAULT 0,
    expected_side_effect_hash CHAR(64) NULL,
    failure_class ENUM('transient', 'permanent', 'ambiguous') NULL,
    error_code VARCHAR(100) NULL,
    error_summary VARCHAR(1000) NULL,
    recovery_required TINYINT(1) NOT NULL DEFAULT 0,
    job_id BIGINT UNSIGNED NULL,
    worker_id VARCHAR(120) NULL,
    fencing_token BIGINT UNSIGNED NULL,
    replay_count INT UNSIGNED NOT NULL DEFAULT 0,
    replay_operator VARCHAR(160) NULL,
    replay_reason VARCHAR(500) NULL,
    last_replayed_at DATETIME(6) NULL,
    occurred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    dispatched_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_platform_outbox_event_key (event_key),
    UNIQUE KEY uq_platform_outbox_idempotency (idempotency_key),
    KEY idx_platform_outbox_dispatch (status, occurred_at, id),
    KEY idx_platform_outbox_transaction (business_transaction_key, id),
    KEY idx_platform_outbox_source_change (source_change_key, occurred_at),
    KEY idx_platform_outbox_recovery (recovery_required, status, updated_at),
    KEY idx_platform_outbox_lease (job_id, fencing_token),
    CONSTRAINT fk_platform_outbox_job FOREIGN KEY (job_id) REFERENCES platform_jobs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS platform_side_effect_receipts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    outbox_event_key VARCHAR(160) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    effect_type VARCHAR(96) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    status ENUM('pending', 'processing', 'confirmed', 'failed') NOT NULL DEFAULT 'pending',
    job_id BIGINT UNSIGNED NULL,
    worker_id VARCHAR(120) NULL,
    fencing_token BIGINT UNSIGNED NULL,
    result_json LONGTEXT NULL,
    failure_class ENUM('transient', 'permanent', 'ambiguous') NULL,
    error_code VARCHAR(100) NULL,
    error_summary VARCHAR(1000) NULL,
    recovery_required TINYINT(1) NOT NULL DEFAULT 0,
    compensation_status ENUM('requested', 'running', 'compensated', 'failed') NULL,
    compensation_operator VARCHAR(160) NULL,
    compensation_reason VARCHAR(500) NULL,
    compensation_result_json LONGTEXT NULL,
    compensation_error_code VARCHAR(100) NULL,
    compensation_error_summary VARCHAR(1000) NULL,
    compensation_requested_at DATETIME(6) NULL,
    compensation_completed_at DATETIME(6) NULL,
    occurred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    confirmed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_platform_side_effect_idempotency (effect_type, idempotency_key),
    KEY idx_platform_side_effect_event (outbox_event_key, occurred_at),
    KEY idx_platform_side_effect_status (status, occurred_at),
    KEY idx_platform_side_effect_lease (job_id, fencing_token),
    KEY idx_platform_side_effect_compensation (compensation_status, updated_at),
    CONSTRAINT fk_platform_side_effect_outbox FOREIGN KEY (outbox_event_key) REFERENCES platform_outbox_events(event_key),
    CONSTRAINT fk_platform_side_effect_job FOREIGN KEY (job_id) REFERENCES platform_jobs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
