CREATE TABLE IF NOT EXISTS `drill_plans` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `domain_id` BIGINT UNSIGNED NOT NULL,
    `process_version_id` BIGINT UNSIGNED NOT NULL,
    `plan_code` VARCHAR(64) NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `plan_type` ENUM('focused_practice', 'comprehensive_certification') NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
    `pass_policy_json` JSON NOT NULL,
    `prerequisite_policy_json` JSON DEFAULT NULL,
    `recording_retention_days` SMALLINT UNSIGNED NOT NULL DEFAULT 180,
    `minimum_client_version` VARCHAR(32) DEFAULT NULL,
    `source_type` VARCHAR(64) NOT NULL,
    `source_ref` VARCHAR(255) DEFAULT NULL,
    `created_by` BIGINT UNSIGNED NOT NULL,
    `updated_by` BIGINT UNSIGNED NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_plans_domain_code` (`domain_id`, `plan_code`),
    KEY `idx_drill_plans_domain_status_type` (`domain_id`, `status`, `plan_type`),
    CONSTRAINT `fk_drill_plans_domain` FOREIGN KEY (`domain_id`) REFERENCES `drill_training_domains` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_plans_process` FOREIGN KEY (`process_version_id`) REFERENCES `drill_process_versions` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_plans_retention` CHECK (`recording_retention_days` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_plan_items` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `plan_id` BIGINT UNSIGNED NOT NULL,
    `scenario_version_id` BIGINT UNSIGNED NOT NULL,
    `rubric_version_id` BIGINT UNSIGNED NOT NULL,
    `sort_order` SMALLINT UNSIGNED NOT NULL,
    `required` TINYINT(1) NOT NULL DEFAULT 1,
    `evaluation_context` ENUM('ai_roleplay', 'training_demo', 'real_call_review') NOT NULL DEFAULT 'ai_roleplay',
    `pass_policy_json` JSON DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_plan_items_order` (`plan_id`, `sort_order`),
    UNIQUE KEY `uk_drill_plan_items_scenario` (`plan_id`, `scenario_version_id`),
    KEY `idx_drill_plan_items_versions` (`scenario_version_id`, `rubric_version_id`),
    CONSTRAINT `fk_drill_plan_items_plan` FOREIGN KEY (`plan_id`) REFERENCES `drill_plans` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_plan_items_scenario` FOREIGN KEY (`scenario_version_id`) REFERENCES `drill_scenario_versions` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_plan_items_rubric` FOREIGN KEY (`rubric_version_id`) REFERENCES `drill_rubric_versions` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_plan_target_scopes` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `plan_id` BIGINT UNSIGNED NOT NULL,
    `target_type` ENUM('position', 'store', 'staff', 'growth_stage') NOT NULL,
    `target_key` VARCHAR(128) NOT NULL,
    `include_mode` ENUM('include', 'exclude') NOT NULL DEFAULT 'include',
    `source_ref` VARCHAR(255) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_plan_targets_identity` (`plan_id`, `target_type`, `target_key`, `include_mode`),
    KEY `idx_drill_plan_targets_lookup` (`target_type`, `target_key`, `plan_id`),
    CONSTRAINT `fk_drill_plan_targets_plan` FOREIGN KEY (`plan_id`) REFERENCES `drill_plans` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_plan_publications` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `plan_id` BIGINT UNSIGNED NOT NULL,
    `publication_no` INT UNSIGNED NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
    `target_scope_json` JSON NOT NULL,
    `starts_at` DATETIME NOT NULL,
    `due_at` DATETIME NOT NULL,
    `published_by` BIGINT UNSIGNED DEFAULT NULL,
    `published_at` DATETIME DEFAULT NULL,
    `cancelled_by` BIGINT UNSIGNED DEFAULT NULL,
    `cancelled_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_plan_publications_version` (`plan_id`, `publication_no`),
    KEY `idx_drill_plan_publications_window` (`status`, `starts_at`, `due_at`),
    CONSTRAINT `fk_drill_plan_publications_plan` FOREIGN KEY (`plan_id`) REFERENCES `drill_plans` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_plan_publication_window` CHECK (`due_at` >= `starts_at`),
    CONSTRAINT `chk_drill_plan_publication_state` CHECK ((`status` = 'published' AND `published_by` IS NOT NULL AND `published_at` IS NOT NULL) OR (`status` <> 'published'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_publication_reviewers` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `publication_id` BIGINT UNSIGNED NOT NULL,
    `reviewer_staff_id` BIGINT UNSIGNED NOT NULL,
    `priority` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    `assigned_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `invalidated_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_publication_reviewers_staff` (`publication_id`, `reviewer_staff_id`),
    KEY `idx_drill_publication_reviewers_queue` (`reviewer_staff_id`, `status`, `priority`),
    CONSTRAINT `fk_drill_publication_reviewers_publication` FOREIGN KEY (`publication_id`) REFERENCES `drill_plan_publications` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_publication_snapshots` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `publication_id` BIGINT UNSIGNED NOT NULL,
    `snapshot_type` VARCHAR(64) NOT NULL,
    `snapshot_key` VARCHAR(128) NOT NULL,
    `version_id` BIGINT UNSIGNED DEFAULT NULL,
    `content_hash` CHAR(64) NOT NULL,
    `snapshot_json` JSON NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_publication_snapshots_key` (`publication_id`, `snapshot_type`, `snapshot_key`),
    KEY `idx_drill_publication_snapshots_version` (`snapshot_type`, `version_id`),
    CONSTRAINT `fk_drill_publication_snapshots_publication` FOREIGN KEY (`publication_id`) REFERENCES `drill_plan_publications` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_assignments` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `publication_id` BIGINT UNSIGNED NOT NULL,
    `staff_id` BIGINT UNSIGNED NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'assigned',
    `failed_attempts` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `current_attempt_id` BIGINT UNSIGNED DEFAULT NULL,
    `starts_at` DATETIME NOT NULL,
    `due_at` DATETIME NOT NULL,
    `completed_at` DATETIME DEFAULT NULL,
    `status_version` INT UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_assignments_publication_staff` (`publication_id`, `staff_id`),
    KEY `idx_drill_assignments_staff_status_due` (`staff_id`, `status`, `due_at`),
    KEY `idx_drill_assignments_current_attempt` (`current_attempt_id`),
    CONSTRAINT `fk_drill_assignments_publication` FOREIGN KEY (`publication_id`) REFERENCES `drill_plan_publications` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_assignments_window` CHECK (`due_at` >= `starts_at`),
    CONSTRAINT `chk_drill_assignments_completion` CHECK ((`status` IN ('passed', 'failed') AND `completed_at` IS NOT NULL) OR (`status` NOT IN ('passed', 'failed')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_attempts` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `assignment_id` BIGINT UNSIGNED DEFAULT NULL,
    `plan_id` BIGINT UNSIGNED DEFAULT NULL,
    `plan_item_id` BIGINT UNSIGNED DEFAULT NULL,
    `staff_id` BIGINT UNSIGNED NOT NULL,
    `domain_id` BIGINT UNSIGNED NOT NULL,
    `process_version_id` BIGINT UNSIGNED NOT NULL,
    `scenario_version_id` BIGINT UNSIGNED NOT NULL,
    `rubric_version_id` BIGINT UNSIGNED NOT NULL,
    `calibration_version_id` BIGINT UNSIGNED DEFAULT NULL,
    `practice_type` ENUM('required', 'self_practice', 'free_chat', 'stage_practice', 'full_process') NOT NULL,
    `evaluation_context` ENUM('ai_roleplay', 'training_demo', 'real_call_review') NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'created',
    `persona_snapshot_json` JSON NOT NULL,
    `persona_snapshot_hash` CHAR(64) NOT NULL,
    `scenario_snapshot_json` JSON NOT NULL,
    `rubric_snapshot_json` JSON NOT NULL,
    `session_goal_json` JSON NOT NULL,
    `current_stage_id` BIGINT UNSIGNED DEFAULT NULL,
    `last_completed_turn_no` INT UNSIGNED NOT NULL DEFAULT 0,
    `status_version` INT UNSIGNED NOT NULL DEFAULT 1,
    `started_at` DATETIME DEFAULT NULL,
    `completed_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_attempts_id_scope` (`id`, `domain_id`),
    KEY `idx_drill_attempts_assignment_status` (`assignment_id`, `status`, `created_at`),
    KEY `idx_drill_attempts_staff_status` (`staff_id`, `status`, `created_at`),
    KEY `idx_drill_attempts_scoring_context` (`evaluation_context`, `rubric_version_id`, `status`),
    CONSTRAINT `fk_drill_attempts_assignment` FOREIGN KEY (`assignment_id`) REFERENCES `drill_assignments` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_attempts_plan` FOREIGN KEY (`plan_id`) REFERENCES `drill_plans` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_attempts_plan_item` FOREIGN KEY (`plan_item_id`) REFERENCES `drill_plan_items` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_attempts_domain` FOREIGN KEY (`domain_id`) REFERENCES `drill_training_domains` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_attempts_process` FOREIGN KEY (`process_version_id`) REFERENCES `drill_process_versions` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_attempts_scenario` FOREIGN KEY (`scenario_version_id`) REFERENCES `drill_scenario_versions` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_attempts_rubric` FOREIGN KEY (`rubric_version_id`) REFERENCES `drill_rubric_versions` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_attempts_stage` FOREIGN KEY (`current_stage_id`) REFERENCES `drill_process_stages` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_attempts_completion` CHECK ((`status` = 'completed' AND `completed_at` IS NOT NULL) OR (`status` <> 'completed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_attempt_participants` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `participant_key` VARCHAR(64) NOT NULL,
    `staff_id` BIGINT UNSIGNED DEFAULT NULL,
    `role_code` VARCHAR(64) NOT NULL,
    `source_type` VARCHAR(32) NOT NULL,
    `mapping_status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `mapping_confidence` DECIMAL(5, 4) DEFAULT NULL,
    `confirmed_by` BIGINT UNSIGNED DEFAULT NULL,
    `confirmed_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_attempt_participants_key` (`attempt_id`, `participant_key`),
    KEY `idx_drill_attempt_participants_role` (`attempt_id`, `role_code`, `mapping_status`),
    CONSTRAINT `fk_drill_attempt_participants_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_participants_confidence` CHECK (`mapping_confidence` IS NULL OR (`mapping_confidence` >= 0 AND `mapping_confidence` <= 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_attempt_score_subjects` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `participant_key` VARCHAR(64) NOT NULL,
    `subject_type` VARCHAR(32) NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending_confirmation',
    `confirmed_by` BIGINT UNSIGNED DEFAULT NULL,
    `confirmed_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_attempt_score_subjects_id_attempt` (`id`, `attempt_id`),
    UNIQUE KEY `uk_drill_attempt_score_subjects_type` (`attempt_id`, `subject_type`),
    KEY `idx_drill_attempt_score_subjects_status` (`attempt_id`, `status`),
    CONSTRAINT `fk_drill_score_subject_participant` FOREIGN KEY (`attempt_id`, `participant_key`) REFERENCES `drill_attempt_participants` (`attempt_id`, `participant_key`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_score_subject_confirmed` CHECK ((`status` = 'confirmed' AND `confirmed_by` IS NOT NULL AND `confirmed_at` IS NOT NULL) OR (`status` <> 'confirmed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_attempt_reference_bindings` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `material_version_id` BIGINT UNSIGNED NOT NULL,
    `purpose_code` VARCHAR(64) NOT NULL,
    `content_hash` CHAR(64) NOT NULL,
    `binding_snapshot_json` JSON NOT NULL,
    `bound_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_attempt_reference_binding` (`attempt_id`, `material_version_id`, `purpose_code`),
    KEY `idx_drill_attempt_reference_version` (`material_version_id`, `attempt_id`),
    CONSTRAINT `fk_drill_attempt_reference_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_audio_assets` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `staff_id` BIGINT UNSIGNED NOT NULL,
    `asset_type` VARCHAR(32) NOT NULL DEFAULT 'turn_recording',
    `storage_path` VARCHAR(500) NOT NULL,
    `public_locator` VARCHAR(500) DEFAULT NULL,
    `mime_type` VARCHAR(100) NOT NULL,
    `byte_size` BIGINT UNSIGNED NOT NULL,
    `duration_ms` INT UNSIGNED DEFAULT NULL,
    `checksum` CHAR(64) NOT NULL,
    `consent_status` VARCHAR(32) NOT NULL DEFAULT 'not_required',
    `consent_basis` VARCHAR(255) DEFAULT NULL,
    `purpose_code` VARCHAR(64) NOT NULL,
    `access_scope_json` JSON NOT NULL,
    `consent_valid_until` DATETIME DEFAULT NULL,
    `retention_until` DATETIME NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'uploading',
    `expired_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_audio_assets_id_attempt` (`id`, `attempt_id`),
    UNIQUE KEY `uk_drill_audio_assets_checksum` (`attempt_id`, `checksum`),
    KEY `idx_drill_audio_assets_retention` (`status`, `retention_until`),
    CONSTRAINT `fk_drill_audio_assets_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_audio_consent` CHECK ((`consent_status` = 'granted' AND `consent_basis` IS NOT NULL AND `consent_valid_until` IS NOT NULL) OR (`consent_status` <> 'granted')),
    CONSTRAINT `chk_drill_audio_expired` CHECK ((`status` = 'expired' AND `expired_at` IS NOT NULL) OR (`status` <> 'expired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_audio_chunks` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `audio_asset_id` BIGINT UNSIGNED NOT NULL,
    `chunk_no` INT UNSIGNED NOT NULL,
    `checksum` CHAR(64) NOT NULL,
    `byte_size` INT UNSIGNED NOT NULL,
    `storage_path` VARCHAR(500) NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'received',
    `received_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_audio_chunks_sequence` (`audio_asset_id`, `chunk_no`),
    KEY `idx_drill_audio_chunks_status` (`audio_asset_id`, `status`, `chunk_no`),
    CONSTRAINT `fk_drill_audio_chunks_asset` FOREIGN KEY (`audio_asset_id`) REFERENCES `drill_audio_assets` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_audio_chunks_number` CHECK (`chunk_no` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_turns` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `turn_no` INT UNSIGNED NOT NULL,
    `stage_id` BIGINT UNSIGNED DEFAULT NULL,
    `speaker` ENUM('employee', 'customer', 'system') NOT NULL,
    `input_type` ENUM('audio', 'text', 'generated') NOT NULL,
    `content` MEDIUMTEXT DEFAULT NULL,
    `audio_asset_id` BIGINT UNSIGNED DEFAULT NULL,
    `transcription_status` VARCHAR(32) NOT NULL DEFAULT 'not_required',
    `generation_metadata_json` JSON DEFAULT NULL,
    `finalized_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_turns_attempt_turn` (`attempt_id`, `turn_no`),
    UNIQUE KEY `uk_drill_turns_id_attempt` (`id`, `attempt_id`),
    KEY `idx_drill_turns_attempt_stage` (`attempt_id`, `stage_id`, `turn_no`),
    CONSTRAINT `fk_drill_turns_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_turns_stage` FOREIGN KEY (`stage_id`) REFERENCES `drill_process_stages` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_turns_audio_attempt` FOREIGN KEY (`audio_asset_id`, `attempt_id`) REFERENCES `drill_audio_assets` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_turns_number` CHECK (`turn_no` > 0),
    CONSTRAINT `chk_drill_turns_input` CHECK ((`input_type` = 'audio' AND `audio_asset_id` IS NOT NULL) OR (`input_type` <> 'audio'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_transcripts` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `audio_asset_id` BIGINT UNSIGNED NOT NULL,
    `turn_id` BIGINT UNSIGNED DEFAULT NULL,
    `transcript_type` ENUM('partial', 'final', 'speaker_mapped') NOT NULL,
    `provider` VARCHAR(64) NOT NULL,
    `model` VARCHAR(128) DEFAULT NULL,
    `content` MEDIUMTEXT DEFAULT NULL,
    `confidence` DECIMAL(5, 4) DEFAULT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `raw_response_ref` VARCHAR(500) DEFAULT NULL,
    `completed_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_transcripts_id_attempt` (`id`, `attempt_id`),
    UNIQUE KEY `uk_drill_transcripts_asset_type` (`audio_asset_id`, `transcript_type`),
    KEY `idx_drill_transcripts_attempt_status` (`attempt_id`, `status`, `transcript_type`),
    CONSTRAINT `fk_drill_transcripts_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_transcripts_audio_attempt` FOREIGN KEY (`audio_asset_id`, `attempt_id`) REFERENCES `drill_audio_assets` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_transcripts_turn_attempt` FOREIGN KEY (`turn_id`, `attempt_id`) REFERENCES `drill_turns` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_transcripts_confidence` CHECK (`confidence` IS NULL OR (`confidence` >= 0 AND `confidence` <= 1)),
    CONSTRAINT `chk_drill_transcripts_completed` CHECK ((`status` = 'completed' AND `completed_at` IS NOT NULL) OR (`status` <> 'completed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_transcript_segments` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `transcript_id` BIGINT UNSIGNED NOT NULL,
    `segment_no` INT UNSIGNED NOT NULL,
    `speaker_key` VARCHAR(64) NOT NULL,
    `role_code` VARCHAR(64) DEFAULT NULL,
    `starts_ms` INT UNSIGNED NOT NULL,
    `ends_ms` INT UNSIGNED NOT NULL,
    `content` TEXT NOT NULL,
    `mapping_confidence` DECIMAL(5, 4) DEFAULT NULL,
    `mapping_status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `is_coach_supplement` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_transcript_segments_id_attempt` (`id`, `attempt_id`),
    UNIQUE KEY `uk_drill_transcript_segments_order` (`transcript_id`, `segment_no`),
    KEY `idx_drill_transcript_segments_speaker` (`attempt_id`, `speaker_key`, `starts_ms`),
    CONSTRAINT `fk_drill_transcript_segments_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_transcript_segments_transcript` FOREIGN KEY (`transcript_id`, `attempt_id`) REFERENCES `drill_transcripts` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_transcript_segments_participant` FOREIGN KEY (`attempt_id`, `speaker_key`) REFERENCES `drill_attempt_participants` (`attempt_id`, `participant_key`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_transcript_segment_range` CHECK (`ends_ms` >= `starts_ms`),
    CONSTRAINT `chk_drill_segment_confidence` CHECK (`mapping_confidence` IS NULL OR (`mapping_confidence` >= 0 AND `mapping_confidence` <= 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_evaluations` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `score_subject_id` BIGINT UNSIGNED NOT NULL,
    `rubric_version_id` BIGINT UNSIGNED NOT NULL,
    `calibration_version_id` BIGINT UNSIGNED DEFAULT NULL,
    `evaluation_context` ENUM('ai_roleplay', 'training_demo', 'real_call_review') NOT NULL,
    `source` ENUM('ai', 'rule', 'hybrid') NOT NULL,
    `total_score` DECIMAL(8, 2) DEFAULT NULL,
    `dimension_scores_json` JSON DEFAULT NULL,
    `critical_results_json` JSON DEFAULT NULL,
    `suggestions_json` JSON DEFAULT NULL,
    `raw_response_ref` VARCHAR(500) DEFAULT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `failure_code` VARCHAR(64) DEFAULT NULL,
    `completed_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_evaluations_id_attempt` (`id`, `attempt_id`),
    UNIQUE KEY `uk_drill_evaluations_subject_source` (`attempt_id`, `score_subject_id`, `source`, `rubric_version_id`),
    KEY `idx_drill_evaluations_attempt_status` (`attempt_id`, `status`, `evaluation_context`),
    CONSTRAINT `fk_drill_evaluations_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_evaluations_subject_attempt` FOREIGN KEY (`score_subject_id`, `attempt_id`) REFERENCES `drill_attempt_score_subjects` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_evaluations_rubric` FOREIGN KEY (`rubric_version_id`) REFERENCES `drill_rubric_versions` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_evaluations_score` CHECK (`total_score` IS NULL OR (`total_score` >= 0 AND `total_score` <= 100)),
    CONSTRAINT `chk_drill_evaluations_completed` CHECK ((`status` = 'completed' AND `total_score` IS NOT NULL AND `completed_at` IS NOT NULL) OR (`status` <> 'completed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_evaluation_evidence` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `evaluation_id` BIGINT UNSIGNED NOT NULL,
    `segment_id` BIGINT UNSIGNED NOT NULL,
    `rubric_version_id` BIGINT UNSIGNED NOT NULL,
    `dimension_code` VARCHAR(64) NOT NULL,
    `criterion_code` VARCHAR(64) DEFAULT NULL,
    `evidence_type` VARCHAR(32) NOT NULL,
    `quoted_text` TEXT NOT NULL,
    `speaker_role` VARCHAR(64) NOT NULL,
    `starts_ms` INT UNSIGNED NOT NULL,
    `ends_ms` INT UNSIGNED NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'supported',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_evaluation_evidence_segment` (`evaluation_id`, `dimension_code`, `segment_id`, `evidence_type`),
    KEY `idx_drill_evaluation_evidence_attempt` (`attempt_id`, `dimension_code`, `starts_ms`),
    CONSTRAINT `fk_drill_evidence_evaluation_attempt` FOREIGN KEY (`evaluation_id`, `attempt_id`) REFERENCES `drill_evaluations` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_evidence_segment_attempt` FOREIGN KEY (`segment_id`, `attempt_id`) REFERENCES `drill_transcript_segments` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_evidence_rubric` FOREIGN KEY (`rubric_version_id`) REFERENCES `drill_rubric_versions` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_evidence_range` CHECK (`ends_ms` >= `starts_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_evaluation_reports` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `evaluation_id` BIGINT UNSIGNED NOT NULL,
    `evaluation_context` ENUM('ai_roleplay', 'training_demo', 'real_call_review') NOT NULL,
    `evaluation_grade` ENUM('excellent', 'good', 'qualified', 'unqualified') DEFAULT NULL,
    `readiness_status` VARCHAR(32) DEFAULT NULL,
    `readiness_rule_version` VARCHAR(64) DEFAULT NULL,
    `readiness_details_json` JSON DEFAULT NULL,
    `report_json` JSON NOT NULL,
    `reference_snapshot_json` JSON NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
    `published_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_evaluation_reports_evaluation` (`evaluation_id`),
    KEY `idx_drill_evaluation_reports_attempt` (`attempt_id`, `status`, `evaluation_context`),
    CONSTRAINT `fk_drill_reports_evaluation_attempt` FOREIGN KEY (`evaluation_id`, `attempt_id`) REFERENCES `drill_evaluations` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_reports_published` CHECK ((`status` = 'published' AND `published_at` IS NOT NULL) OR (`status` <> 'published'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_report_action_items` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `report_id` BIGINT UNSIGNED NOT NULL,
    `dimension_code` VARCHAR(64) NOT NULL,
    `action_text` VARCHAR(1000) NOT NULL,
    `success_criteria` VARCHAR(1000) NOT NULL,
    `due_at` DATETIME NOT NULL,
    `retest_method` VARCHAR(500) NOT NULL,
    `learning_resource_id` BIGINT UNSIGNED NOT NULL,
    `learning_resource_version` VARCHAR(64) NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'assigned',
    `completed_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_drill_report_actions_report_status` (`report_id`, `status`, `due_at`),
    KEY `idx_drill_report_actions_resource` (`learning_resource_id`, `learning_resource_version`),
    CONSTRAINT `fk_drill_report_actions_report` FOREIGN KEY (`report_id`) REFERENCES `drill_evaluation_reports` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_report_actions_complete` CHECK ((`status` = 'completed' AND `completed_at` IS NOT NULL) OR (`status` <> 'completed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_review_tasks` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `assignment_id` BIGINT UNSIGNED NOT NULL,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `evaluation_id` BIGINT UNSIGNED NOT NULL,
    `reviewer_staff_id` BIGINT UNSIGNED NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `decision` ENUM('passed', 'retry', 'coaching_required') DEFAULT NULL,
    `comment` VARCHAR(2000) DEFAULT NULL,
    `ai_score` DECIMAL(8, 2) NOT NULL,
    `final_score` DECIMAL(8, 2) DEFAULT NULL,
    `score_adjustment_json` JSON DEFAULT NULL,
    `adjustment_reason` VARCHAR(1000) DEFAULT NULL,
    `reviewed_at` DATETIME DEFAULT NULL,
    `superseded_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_review_tasks_attempt` (`attempt_id`),
    UNIQUE KEY `uk_drill_review_tasks_id_attempt` (`id`, `attempt_id`),
    KEY `idx_drill_review_tasks_reviewer_queue` (`reviewer_staff_id`, `status`, `created_at`),
    CONSTRAINT `fk_drill_review_tasks_assignment` FOREIGN KEY (`assignment_id`) REFERENCES `drill_assignments` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_review_tasks_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_review_tasks_evaluation_attempt` FOREIGN KEY (`evaluation_id`, `attempt_id`) REFERENCES `drill_evaluations` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_review_scores` CHECK (`ai_score` >= 0 AND `ai_score` <= 100 AND (`final_score` IS NULL OR (`final_score` >= 0 AND `final_score` <= 100))),
    CONSTRAINT `chk_drill_review_decision` CHECK ((`status` = 'completed' AND `decision` IS NOT NULL AND `final_score` IS NOT NULL AND `reviewed_at` IS NOT NULL) OR (`status` <> 'completed')),
    CONSTRAINT `chk_drill_review_adjustment` CHECK (`final_score` IS NULL OR `final_score` = `ai_score` OR `adjustment_reason` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_coaching_tasks` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `assignment_id` BIGINT UNSIGNED NOT NULL,
    `coach_staff_id` BIGINT UNSIGNED NOT NULL,
    `trigger_attempt_id` BIGINT UNSIGNED NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'open',
    `active_assignment_id` BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN `status` IN ('open', 'in_progress') THEN `assignment_id` ELSE NULL END) STORED,
    `failure_count_snapshot` SMALLINT UNSIGNED NOT NULL,
    `notes` VARCHAR(4000) DEFAULT NULL,
    `completed_at` DATETIME DEFAULT NULL,
    `reopened_at` DATETIME DEFAULT NULL,
    `closed_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_coaching_tasks_active` (`active_assignment_id`),
    KEY `idx_drill_coaching_tasks_coach` (`coach_staff_id`, `status`, `created_at`),
    CONSTRAINT `fk_drill_coaching_tasks_assignment` FOREIGN KEY (`assignment_id`) REFERENCES `drill_assignments` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_coaching_tasks_attempt` FOREIGN KEY (`trigger_attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_coaching_trigger` CHECK (`failure_count_snapshot` >= 3),
    CONSTRAINT `chk_drill_coaching_complete` CHECK ((`status` = 'completed' AND `completed_at` IS NOT NULL) OR (`status` <> 'completed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_certifications` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `certification_no` VARCHAR(64) NOT NULL,
    `assignment_id` BIGINT UNSIGNED NOT NULL,
    `attempt_id` BIGINT UNSIGNED NOT NULL,
    `review_task_id` BIGINT UNSIGNED NOT NULL,
    `evaluation_id` BIGINT UNSIGNED NOT NULL,
    `plan_id` BIGINT UNSIGNED NOT NULL,
    `staff_id` BIGINT UNSIGNED NOT NULL,
    `reviewer_staff_id` BIGINT UNSIGNED NOT NULL,
    `ai_score` DECIMAL(8, 2) NOT NULL,
    `final_score` DECIMAL(8, 2) NOT NULL,
    `critical_results_json` JSON NOT NULL,
    `result_snapshot_json` JSON NOT NULL,
    `certified_at` DATETIME NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_certifications_no` (`certification_no`),
    UNIQUE KEY `uk_drill_certifications_assignment` (`assignment_id`),
    UNIQUE KEY `uk_drill_certifications_attempt` (`attempt_id`),
    KEY `idx_drill_certifications_staff_plan` (`staff_id`, `plan_id`, `certified_at`),
    CONSTRAINT `fk_drill_certifications_assignment` FOREIGN KEY (`assignment_id`) REFERENCES `drill_assignments` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_certifications_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `drill_attempts` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_certifications_review_attempt` FOREIGN KEY (`review_task_id`, `attempt_id`) REFERENCES `drill_review_tasks` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_certifications_evaluation_attempt` FOREIGN KEY (`evaluation_id`, `attempt_id`) REFERENCES `drill_evaluations` (`id`, `attempt_id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_drill_certifications_plan` FOREIGN KEY (`plan_id`) REFERENCES `drill_plans` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_drill_certification_scores` CHECK (`ai_score` >= 0 AND `ai_score` <= 100 AND `final_score` >= 0 AND `final_score` <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_notifications` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `notification_key` VARCHAR(128) NOT NULL,
    `recipient_staff_id` BIGINT UNSIGNED NOT NULL,
    `notification_type` VARCHAR(64) NOT NULL,
    `object_type` VARCHAR(64) NOT NULL,
    `object_id` BIGINT UNSIGNED NOT NULL,
    `channel` VARCHAR(32) NOT NULL,
    `payload_json` JSON NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `available_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `sent_at` DATETIME DEFAULT NULL,
    `read_at` DATETIME DEFAULT NULL,
    `failure_message` VARCHAR(1000) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_drill_notifications_key` (`notification_key`),
    KEY `idx_drill_notifications_recipient` (`recipient_staff_id`, `status`, `available_at`),
    KEY `idx_drill_notifications_object` (`object_type`, `object_id`),
    CONSTRAINT `chk_drill_notifications_sent` CHECK ((`status` = 'sent' AND `sent_at` IS NOT NULL) OR (`status` <> 'sent'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `drill_audit_logs` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `request_id` VARCHAR(64) DEFAULT NULL,
    `actor_user_id` BIGINT UNSIGNED DEFAULT NULL,
    `actor_staff_id` BIGINT UNSIGNED DEFAULT NULL,
    `action` VARCHAR(128) NOT NULL,
    `object_type` VARCHAR(64) NOT NULL,
    `object_id` BIGINT UNSIGNED DEFAULT NULL,
    `before_snapshot_json` JSON DEFAULT NULL,
    `after_snapshot_json` JSON DEFAULT NULL,
    `reason` VARCHAR(1000) DEFAULT NULL,
    `context_json` JSON DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_drill_audit_logs_object` (`object_type`, `object_id`, `created_at`),
    KEY `idx_drill_audit_logs_actor` (`actor_staff_id`, `created_at`),
    KEY `idx_drill_audit_logs_action` (`action`, `created_at`),
    KEY `idx_drill_audit_logs_request` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
