(function () {
  'use strict';
  var state = { tasks: [], currentId: 0, detail: null };
  var $ = function (id) { return document.getElementById(id); };
  var esc = function (value) { var node = document.createElement('div'); node.textContent = String(value == null ? '' : value); return node.innerHTML; };
  function authFetch(url, options) { if (window.AppAuth && window.AppAuth.authFetch) return window.AppAuth.authFetch(url, options); var requestOptions = Object.assign({}, options || {}); requestOptions.headers = window.authHeaders ? window.authHeaders(requestOptions.headers || {}) : requestOptions.headers; return fetch(url, requestOptions); }
  async function request(url, options) { var response = await authFetch(url, options || {}); var result = await response.json().catch(function () { return {}; }); if (!response.ok || Number(result.code) !== 0) throw new Error(result.message || '请求失败'); return result.data || {}; }
  function post(url, body) { return request(url, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID ? crypto.randomUUID() : String(Date.now()) }, body: JSON.stringify(body) }); }
  function notify(message, bad) { $('notice').textContent = message; $('notice').className = 'notice show' + (bad ? ' bad' : ''); clearTimeout(notify.timer); notify.timer = setTimeout(function () { $('notice').className = 'notice'; }, 4500); }
  function setBusy(value) { document.body.classList.toggle('loading', value); }
  function stageLabel(value) { return { store_review: '店长初审', supervisor_review: '教学主管终审' }[value] || value || '-'; }
  function statusLabel(value) { return { pending: '待处理', completed: '已处理', approved: '已通过', returned: '已退回', accepted: '已采纳', ignored: '已忽略' }[value] || value || '-'; }
  function text(value) { if (Array.isArray(value)) return value.map(function (item) { return typeof item === 'object' ? item.name || item.title || item.value || JSON.stringify(item) : item; }).join('、'); return String(value || '未填写'); }
  function meta(label, value) { return '<div class="meta-box"><span>' + esc(label) + '</span><strong>' + esc(value || '-') + '</strong></div>'; }
  function card(title, value, wide) { return '<article class="content-card' + (wide ? ' wide' : '') + '"><h3>' + esc(title) + '</h3><p>' + esc(text(value)) + '</p></article>'; }
  async function loadTasks(selectId) { var query = new URLSearchParams(); if ($('statusFilter').value) query.set('status', $('statusFilter').value); if ($('stageFilter').value) query.set('stage', $('stageFilter').value); var data = await request('/api/lesson-reviews/list.php?' + query.toString()); state.tasks = data.tasks || []; $('pendingCount').textContent = state.tasks.filter(function (task) { return task.status === 'pending'; }).length; $('doneCount').textContent = state.tasks.filter(function (task) { return task.status !== 'pending'; }).length; renderTasks(); var wanted = Number(selectId || state.currentId || new URLSearchParams(location.search).get('id')); if (wanted && state.tasks.some(function (task) { return Number(task.id) === wanted; })) await loadDetail(wanted); else if (state.tasks[0]) await loadDetail(Number(state.tasks[0].id)); else { state.currentId = 0; $('detail').classList.remove('active'); } }
  function renderTasks() { $('taskList').innerHTML = state.tasks.length ? state.tasks.map(function (task) { return '<button class="task' + (Number(task.id) === state.currentId ? ' active' : '') + '" type="button" data-task-id="' + Number(task.id) + '"><strong>' + esc(task.title) + '</strong><span>' + esc(task.store_name) + ' · ' + esc(task.author_name) + '</span><span>' + esc(task.lesson_date) + ' · V' + esc(task.version_no) + '</span><span class="pill">' + esc(stageLabel(task.stage)) + ' · ' + esc(statusLabel(task.status)) + '</span></button>'; }).join('') : '<div class="empty">当前筛选下没有审核任务</div>'; }
  async function loadDetail(id) { var data = await request('/api/lesson-reviews/list.php?id=' + encodeURIComponent(id)); state.currentId = id; state.detail = data; renderTasks(); renderDetail(data); $('detail').classList.add('active'); history.replaceState(null, '', '/lesson-review.html?id=' + encodeURIComponent(id)); }
  function renderDetail(data) { var task = data.task || {}; var content = task.content_json || {}; var objectives = content.objectives || {}; var safety = content.safety || {}; var reflection = content.reflection || {}; $('lessonTitle').textContent = task.title || '未命名教案'; $('lessonSubtitle').textContent = stageLabel(task.stage) + ' · ' + (task.store_name || '-') + ' · ' + (task.author_name || '-'); $('taskStatus').textContent = statusLabel(task.status); $('versionBadge').textContent = '冻结版本 V' + (task.version_no || '-'); $('lessonMeta').innerHTML = meta('课程线', task.course_line) + meta('班级 / 级别', task.class_level) + meta('上课日期', task.lesson_date) + meta('提交状态', statusLabel(task.submission_status)); var phases = Array.isArray(content.phases) ? content.phases : []; $('lessonContent').innerHTML = card('A · 运动能力', objectives.athletic) + card('C · 认知能力', objectives.cognitive) + card('E · 参与动能', objectives.engagement) + card('重点学员', content.learner_focus, true) + card('身体安全', safety.physical) + card('心理安全', safety.psychological) + card('器材', content.equipment) + '<article class="content-card wide"><h3>课程阶段</h3>' + (phases.length ? phases.map(function (phase) { return '<div class="phase"><strong>' + esc(phase.name || phase.title || '阶段') + '</strong><span>' + esc(phase.duration_minutes || phase.duration || 0) + ' 分钟</span><span>' + esc(phase.content || phase.description || '') + '</span></div>'; }).join('') : '<p>未填写</p>') + '</article>' + card('升降阶方案', content.progressions) + card('助教分工', content.assistant_responsibilities) + card('ACE 反思', [reflection.athletic, reflection.cognitive, reflection.engagement].filter(Boolean)); renderEvidence(data); renderHistory(data); var pending = task.status === 'pending'; $('decisionBox').style.display = pending ? '' : 'none'; $('comments').value = task.comments || ''; }
  function renderEvidence(data) { var files = data.source_files || []; var suggestions = data.suggestions || []; $('evidence').innerHTML = '<article class="content-card"><h3>原始文件</h3>' + (files.length ? files.map(function (file) { return '<p>' + esc(file.original_name) + ' · ' + Math.max(1, Math.round(Number(file.byte_size || 0) / 1024)) + ' KB</p>'; }).join('') : '<p>暂无文件</p>') + '</article><article class="content-card wide"><h3>优化建议处理</h3>' + (suggestions.length ? suggestions.map(function (item) { return '<p><strong>' + esc(statusLabel(item.decision)) + '</strong> · ' + esc(item.message || item.reason || item.suggestion_type) + '</p>'; }).join('') : '<p>当前版本暂无建议</p>') + '</article>'; }
  function renderHistory(data) { var versions = data.versions || []; var reviews = data.review_history || []; $('history').innerHTML = reviews.concat(versions.map(function (version) { return { kind: 'version', version_no: version.version_no, version_type: version.version_type, created_at: version.created_at }; })).map(function (item) { if (item.kind === 'version') return '<div class="history-item"><strong>结构化版本 V' + esc(item.version_no) + '</strong><div class="small">' + esc(item.version_type || 'version') + ' · ' + esc(item.created_at || '') + '</div></div>'; return '<div class="history-item"><strong>' + esc(stageLabel(item.stage)) + ' · ' + esc(statusLabel(item.decision || item.status)) + '</strong><div>' + esc(item.comments || '暂无审核意见') + '</div><div class="small">' + esc(item.reviewer_name || item.reviewer_role) + ' · V' + esc(item.version_no || '-') + ' · ' + esc(item.decided_at || item.created_at || '') + '</div></div>'; }).join('') || '<div class="empty">暂无历史记录</div>'; }
  async function decide(decision) { if (!state.detail || !state.currentId) return; var comments = $('comments').value.trim(); if (decision === 'returned' && !comments) throw new Error('退回时请填写具体修改原因'); var result = await post('/api/lesson-reviews/decision.php', { review_task_id: state.currentId, decision: decision, comments: comments }); notify(decision === 'approved' ? '审核已通过，教案已进入下一阶段' : '教案已退回教练修改'); await loadTasks(result.next_review_task_id || state.currentId); }
  async function run(action) { try { setBusy(true); await action(); } catch (error) { notify(error.message || '操作失败', true); } finally { setBusy(false); } }
  $('taskList').addEventListener('click', function (event) { var button = event.target.closest('[data-task-id]'); if (button) run(function () { return loadDetail(Number(button.dataset.taskId)); }); }); $('statusFilter').addEventListener('change', function () { run(loadTasks); }); $('stageFilter').addEventListener('change', function () { run(loadTasks); }); $('refreshButton').addEventListener('click', function () { run(loadTasks); }); $('approveButton').addEventListener('click', function () { run(function () { return decide('approved'); }); }); $('returnButton').addEventListener('click', function () { run(function () { return decide('returned'); }); }); window.requirePageAuth({ onAuthed: function () { run(loadTasks); } });
}());
