<?php
declare(strict_types=1);

require_once __DIR__ . '/DrillContentService.php';
require_once __DIR__ . '/DrillRubricService.php';
require_once __DIR__ . '/DrillReferenceMaterialService.php';
require_once __DIR__ . '/DrillLearningService.php';
require_once __DIR__ . '/DrillPlanService.php';
require_once __DIR__ . '/DrillReviewService.php';
require_once __DIR__ . '/DrillCoachingService.php';
require_once __DIR__ . '/DrillMigrationService.php';

final class DrillAdminApiService
{
    public function __construct(private PDO $pdo) {}

    public function read(string $resource, array $input, array $context, array $staff): array
    {
        return match ($resource) {
            'domains' => ['items' => $this->rows('SELECT * FROM drill_training_domains ORDER BY id')],
            'stages' => ['items' => $this->rows('SELECT stage.*, version.domain_id, version.version_no, version.status AS process_status FROM drill_process_stages stage INNER JOIN drill_process_versions version ON version.id = stage.process_version_id ORDER BY version.domain_id, version.version_no DESC, stage.sort_order')],
            'scenarios' => ['items' => $this->rows('SELECT scenario.*, version.id AS version_id, version.version_no, version.status AS version_status, version.title FROM drill_scenarios scenario INNER JOIN drill_scenario_versions version ON version.scenario_id = scenario.id ORDER BY scenario.id, version.version_no DESC')],
            'rubrics' => ['items' => $this->rows('SELECT rubric.*, version.id AS version_id, version.version_no, version.status AS version_status, version.max_score, version.pass_score FROM drill_rubrics rubric INNER JOIN drill_rubric_versions version ON version.rubric_id = rubric.id ORDER BY rubric.id, version.version_no DESC')],
            'reference-materials' => ['items' => $this->rows('SELECT material.*, version.id AS version_id, version.version_code, version.status AS version_status, version.authorization_status, version.effective_from, version.effective_until FROM drill_reference_materials material INNER JOIN drill_reference_material_versions version ON version.reference_material_id = material.id ORDER BY material.id, version.id DESC')],
            'knowledge-map' => $this->knowledgeMap(),
            'calibrations' => ['items' => $this->rows('SELECT * FROM drill_score_calibration_versions ORDER BY domain_id, rubric_version_id, evaluation_context, version_no DESC')],
            'plans' => ['items' => $this->rows('SELECT plan.*, (SELECT COUNT(*) FROM drill_plan_publications publication WHERE publication.plan_id = plan.id) AS publication_count FROM drill_plans plan ORDER BY plan.id DESC')],
            'reviews' => !empty($input['include_evidence']) ? $this->reviewEvidence((int) ($input['id'] ?? 0), $context, $staff) : ['items' => $this->reviewRows($context, $staff, $input)],
            'coaching' => ['items' => $this->coachingRows($context, $staff, $input)],
            'analytics' => $this->analytics($context, $staff, $input),
            'migrations' => $this->migrationPreflight(),
            default => throw new InvalidArgumentException('未知演练管理资源。'),
        };
    }

    public function write(string $resource, array $input, array $context, array $staff): array
    {
        $actor = (int) ($context['staff_id'] ?? 0);
        $action = (string) ($input['action'] ?? '');
        return match ($resource) {
            'stages' => $this->stagesWrite($action, $input, $actor),
            'scenarios' => $this->scenariosWrite($action, $input, $actor),
            'rubrics' => $this->rubricsWrite($action, $input, $actor),
            'reference-materials' => $this->materialsWrite($action, $input, $actor),
            'knowledge-map' => $this->knowledgeWrite($action, $input, $actor),
            'calibrations' => $this->calibrationWrite($action, $input, $actor),
            'plans' => $this->plansWrite($action, $input, $actor),
            'reviews' => $this->reviewsWrite($action, $input, $context, $staff, $actor),
            'coaching' => $this->coachingWrite($action, $input, $context, $staff, $actor),
            'migrations' => $this->migrationWrite($action, $input),
            default => throw new InvalidArgumentException('该管理资源当前只读或不存在。'),
        };
    }

    private function stagesWrite(string $action, array $input, int $actor): array { $service = new DrillContentService($this->pdo); return match ($action) { 'create_process' => $service->createProcessDraft((int) $input['domain_id'], (string) $input['name'], (array) $input['stages'], $actor, (string) ($input['source_type'] ?? 'manual'), $input['source_ref'] ?? null), 'transition_process' => $service->transitionProcessVersion((int) $input['version_id'], (string) $input['event'], $actor), 'upsert_persona' => $service->upsertPersonaValue((int) $input['domain_id'], (string) $input['dimension_code'], (string) $input['dimension_name'], (string) $input['value_code'], (string) $input['name'], (int) $input['sort_order'], (string) ($input['source_type'] ?? 'manual'), $input['source_ref'] ?? null), default => throw new InvalidArgumentException('不支持的板块操作。') }; }
    private function scenariosWrite(string $action, array $input, int $actor): array { $service = new DrillContentService($this->pdo); return match ($action) { 'create' => $service->createScenarioDraft((int) $input['domain_id'], (int) $input['stage_id'], (string) $input['scenario_code'], (string) $input['name'], (string) $input['difficulty'], (array) $input['payload'], (array) $input['persona'], $actor, (string) ($input['source_type'] ?? 'manual'), $input['source_ref'] ?? null), 'update' => $service->updateScenarioDraft((int) $input['version_id'], (array) $input['payload'], $actor), 'transition' => $service->transitionScenarioVersion((int) $input['version_id'], (string) $input['event'], $actor, $input['reason'] ?? null), 'revise' => $service->reviseScenario((int) $input['version_id'], $actor), default => throw new InvalidArgumentException('不支持的场景操作。') }; }
    private function rubricsWrite(string $action, array $input, int $actor): array { $service = new DrillRubricService($this->pdo); return match ($action) { 'create' => $service->createDraft((int) $input['domain_id'], (int) $input['process_version_id'], (array) $input['config'], (array) $input['mappings'], $actor, (string) ($input['source_type'] ?? 'manual'), $input['source_ref'] ?? null), 'transition' => $service->transitionVersion((int) $input['version_id'], (string) $input['event'], $actor), default => throw new InvalidArgumentException('不支持的评分规则操作。') }; }
    private function materialsWrite(string $action, array $input, int $actor): array { if ($action !== 'publish') throw new InvalidArgumentException('参考资料仅支持发布已审核版本。'); return (new DrillReferenceMaterialService($this->pdo))->publish((int) $input['version_id'], $actor, (string) $input['authorization_reference'], (string) $input['effective_from'], (string) $input['effective_until']); }
    private function knowledgeWrite(string $action, array $input, int $actor): array { $service = new DrillLearningService($this->pdo); return match ($action) { 'create_knowledge' => $service->createKnowledgePointDraft((int) $input['domain_id'], (array) $input['payload'], $actor), 'create_resource' => $service->createLearningResourceDraft((int) $input['domain_id'], (array) $input['payload'], $actor), 'create_mapping' => $service->createMappingDraft((int) $input['domain_id'], (int) $input['rubric_version_id'], (array) $input['links'], $actor), 'transition_knowledge' => $service->transitionKnowledgePointVersion((int) $input['version_id'], (string) $input['event'], $actor), 'transition_resource' => $service->transitionLearningResourceVersion((int) $input['version_id'], (string) $input['event'], $actor), 'transition_mapping' => $service->transitionMappingVersion((int) $input['mapping_version_id'], (string) $input['event'], $actor), default => throw new InvalidArgumentException('不支持的知识图谱操作。') }; }
    private function calibrationWrite(string $action, array $input, int $actor): array { $id = (int) ($input['version_id'] ?? 0); if ($id <= 0) throw new InvalidArgumentException('校准版本 ID 无效。'); if ($action === 'record') { $status = (string) ($input['status'] ?? 'validated'); if (!in_array($status, ['draft', 'validated'], true)) throw new InvalidArgumentException('校准记录状态无效。'); $stmt = $this->pdo->prepare("UPDATE drill_score_calibration_versions SET test_sample_snapshot_json = ?, human_benchmark_snapshot_json = ?, weight_changes_json = ?, threshold_changes_json = ?, version_notes = ?, sample_size = ?, agreement_rate = ?, status = ? WHERE id = ? AND status IN ('draft', 'validated')"); $stmt->execute([$this->json((array) ($input['test_samples'] ?? [])), $this->json((array) ($input['human_comparison'] ?? [])), $this->json((array) ($input['weight_changes'] ?? [])), $this->json((array) ($input['threshold_changes'] ?? [])), (string) ($input['notes'] ?? ''), (int) ($input['sample_size'] ?? 0), (float) ($input['agreement_rate'] ?? 0), $status, $id]); if ($stmt->rowCount() !== 1) throw new DomainException('校准版本不存在或已发布。'); $this->audit($actor, 'calibration.recorded', 'calibration_version', $id, ['status' => 'draft'], ['status' => $status]); return ['version_id' => $id, 'status' => $status]; } if ($action === 'publish') { $stmt = $this->pdo->prepare("UPDATE drill_score_calibration_versions SET status = 'published', published_by_staff_id = ?, published_at = CURRENT_TIMESTAMP WHERE id = ? AND status = 'validated' AND sample_size > 0"); $stmt->execute([$actor, $id]); if ($stmt->rowCount() !== 1) throw new DomainException('校准版本必须先通过验证并包含有效样本。'); $this->audit($actor, 'calibration.published', 'calibration_version', $id, ['status' => 'validated'], ['status' => 'published']); return ['version_id' => $id, 'status' => 'published']; } throw new InvalidArgumentException('不支持的校准操作。'); }
    private function plansWrite(string $action, array $input, int $actor): array { $service = new DrillPlanService($this->pdo); return match ($action) { 'create' => $service->createDraft((int) $input['domain_id'], (int) $input['process_version_id'], (array) $input['definition'], (array) $input['items'], (array) $input['scopes'], $actor), 'publish' => $service->publish((int) $input['plan_id'], (string) $input['publication_key'], new DateTimeImmutable((string) $input['starts_at']), new DateTimeImmutable((string) $input['due_at']), (array) $input['reviewer_staff_ids'], ['drill.plan_publish'], $actor), default => throw new InvalidArgumentException('不支持的计划操作。') }; }
    private function reviewsWrite(string $action, array $input, array $context, array $staff, int $actor): array { $id = (int) ($input['review_task_id'] ?? 0); $service = new DrillReviewService($this->pdo); if ($action === 'confirm_speakers') return $this->confirmScoreSubjects((int) ($input['attempt_id'] ?? 0), (array) ($input['score_subject_keys'] ?? []), $context, $staff, $actor); $this->assertReviewScope($id, $context, $staff); return match ($action) { 'complete' => $service->complete($id, $actor, (string) $input['decision'], (float) $input['final_score'], (string) ($input['comment'] ?? ''), (string) ($input['adjustment_reason'] ?? ''), new DateTimeImmutable('now')), 'reassign' => (function () use ($service, $id, $actor, $input): array { $service->reassign($id, $actor, (int) $input['reviewer_staff_id']); return ['review_task_id' => $id, 'status' => 'reassigned']; })(), default => throw new InvalidArgumentException('不支持的复核操作。') }; }
    private function coachingWrite(string $action, array $input, array $context, array $staff, int $actor): array { if ($action !== 'complete') throw new InvalidArgumentException('不支持的辅导操作。'); $id = (int) ($input['coaching_task_id'] ?? 0); $this->assertCoachingScope($id, $context, $staff); return (new DrillCoachingService($this->pdo))->recordAndReopen($id, $actor, (string) ($input['notes'] ?? ''), new DateTimeImmutable('now')); }
    private function migrationWrite(string $action, array $input): array { $service = new DrillMigrationService($this->pdo); if ($action === 'preflight') return $service->preflight(); if ($action === 'execute') return $service->execute((string) ($input['batch_key'] ?? ''), false); if ($action === 'retry_failed') return $service->execute((string) ($input['batch_key'] ?? ''), true); throw new InvalidArgumentException('不支持的迁移操作。'); }

    private function reviewRows(array $context, array $staff, array $input): array { $scope = $this->scope($context, $staff); $where = []; $params = []; $this->scopeWhere($scope, 'assignment', 'task', $where, $params); if (!empty($input['id'])) { $where[] = 'task.id = ?'; $params[] = (int) $input['id']; } if (!empty($input['status'])) { $where[] = 'task.status = ?'; $params[] = (string) $input['status']; } return $this->rows('SELECT task.*, assignment.staff_id, assignment.status AS assignment_status FROM drill_review_tasks task INNER JOIN drill_assignments assignment ON assignment.id = task.assignment_id' . ($where ? ' WHERE ' . implode(' AND ', $where) : '') . ' ORDER BY task.id DESC', $params); }
    private function reviewEvidence(int $id, array $context, array $staff): array { $this->assertReviewScope($id, $context, $staff); return (new DrillReviewService($this->pdo))->evidence($id); }
    private function confirmScoreSubjects(int $attemptId, array $subjects, array $context, array $staff, int $actor): array { if ($attemptId <= 0 || $subjects === []) throw new InvalidArgumentException('演练实例和评分对象不能为空。'); $scope = $this->scope($context, $staff); $where = ['attempt.id = ?']; $params = [$attemptId]; if ($scope['scope_type'] === 'reviewer') { $where[] = "EXISTS (SELECT 1 FROM drill_plan_publications publication INNER JOIN drill_publication_reviewers reviewer ON reviewer.publication_id = publication.id AND reviewer.reviewer_staff_id = ? AND reviewer.status = 'active' WHERE publication.plan_id = attempt.plan_id)"; $params[] = $scope['staff_id']; } else $this->scopeWhere($scope, 'assignment', 'attempt', $where, $params, null, 'attempt.staff_id'); $attempt = $this->rows('SELECT attempt.id, attempt.status FROM drill_attempts attempt LEFT JOIN drill_assignments assignment ON assignment.id = attempt.assignment_id WHERE ' . implode(' AND ', $where), $params)[0] ?? null; if (!$attempt) throw new DrillAdminScopeDeniedException('演练实例不在当前数据范围内。'); $stmt = $this->pdo->prepare("UPDATE drill_attempt_score_subjects SET status = 'confirmed', confirmed_by = ?, confirmed_at = CURRENT_TIMESTAMP WHERE attempt_id = ? AND participant_key = ?"); foreach ($subjects as $subject) { $subject = trim((string) $subject); if ($subject === '') continue; $stmt->execute([$actor, $attemptId, $subject]); } if ($attempt['status'] === 'speaker_confirmation_required') $this->pdo->prepare("UPDATE drill_attempts SET status = 'evaluating', status_version = status_version + 1 WHERE id = ?")->execute([$attemptId]); $this->audit($actor, 'attempt.speakers_confirmed', 'drill_attempt', $attemptId, [], ['score_subject_keys' => array_values($subjects)]); return ['attempt_id' => $attemptId, 'status' => $attempt['status'] === 'speaker_confirmation_required' ? 'evaluating' : $attempt['status']]; }
    private function coachingRows(array $context, array $staff, array $input): array { $scope = $this->scope($context, $staff); $where = []; $params = []; $this->scopeWhere($scope, 'assignment', 'task', $where, $params, 'coach_staff_id'); if (!empty($input['id'])) { $where[] = 'task.id = ?'; $params[] = (int) $input['id']; } return $this->rows('SELECT task.*, assignment.staff_id, assignment.status AS assignment_status FROM drill_coaching_tasks task INNER JOIN drill_assignments assignment ON assignment.id = task.assignment_id' . ($where ? ' WHERE ' . implode(' AND ', $where) : '') . ' ORDER BY task.id DESC', $params); }
    private function analytics(array $context, array $staff, array $input): array { $scope = $this->scope($context, $staff); $where = ["attempt.status IN ('completed', 'evaluated')"]; $params = []; $this->scopeWhere($scope, 'assignment', 'attempt', $where, $params, null, 'attempt.staff_id'); foreach (['domain_id' => 'attempt.domain_id', 'staff_id' => 'attempt.staff_id', 'stage_id' => 'attempt.current_stage_id'] as $field => $column) { if (!empty($input[$field])) { $where[] = $column . ' = ?'; $params[] = (int) $input[$field]; } } if (!empty($input['date_from'])) { $where[] = 'DATE(COALESCE(attempt.completed_at, attempt.created_at)) >= ?'; $params[] = (string) $input['date_from']; } if (!empty($input['date_to'])) { $where[] = 'DATE(COALESCE(attempt.completed_at, attempt.created_at)) <= ?'; $params[] = (string) $input['date_to']; } if (!empty($input['store_id'])) { $where[] = 'EXISTS (SELECT 1 FROM staff_assignments analytics_store WHERE analytics_store.staff_id = attempt.staff_id AND analytics_store.store_id = ? AND analytics_store.start_date <= CURRENT_DATE AND (analytics_store.end_date IS NULL OR analytics_store.end_date >= CURRENT_DATE))'; $params[] = (int) $input['store_id']; } if (!empty($input['role_code'])) { $where[] = 'EXISTS (SELECT 1 FROM staff_assignments analytics_role INNER JOIN organization_positions position ON position.id = analytics_role.position_id WHERE analytics_role.staff_id = attempt.staff_id AND position.position_code = ? AND analytics_role.start_date <= CURRENT_DATE AND (analytics_role.end_date IS NULL OR analytics_role.end_date >= CURRENT_DATE))'; $params[] = (string) $input['role_code']; } if (!empty($input['plan_or_status'])) { if (ctype_digit((string) $input['plan_or_status'])) { $where[] = 'attempt.plan_id = ?'; $params[] = (int) $input['plan_or_status']; } else { $where[] = 'assignment.status = ?'; $params[] = (string) $input['plan_or_status']; } } $sql = 'SELECT attempt.staff_id, attempt.domain_id, assignment.status, COUNT(*) AS attempts, AVG(evaluation.total_score) AS average_score, COUNT(DISTINCT CASE WHEN assignment.status = \'passed\' THEN attempt.staff_id END) AS passed_staff FROM drill_attempts attempt LEFT JOIN drill_assignments assignment ON assignment.id = attempt.assignment_id LEFT JOIN drill_evaluations evaluation ON evaluation.attempt_id = attempt.id AND evaluation.status = \'completed\' WHERE ' . implode(' AND ', $where) . ' GROUP BY attempt.staff_id, attempt.domain_id, assignment.status'; $items = $this->rows($sql, $params); $staffIds = array_unique(array_map(fn(array $row): int => (int) $row['staff_id'], $items)); return ['items' => $items, 'sample' => ['staff_count' => count($staffIds), 'attempt_count' => count($items), 'low_sample' => count($staffIds) < 3 || count($items) < 10], 'permission_scope' => $scope]; }
    private function migrationPreflight(): array { return (new DrillMigrationService($this->pdo))->preflight(); }
    private function knowledgeMap(): array { return ['knowledge_points' => $this->rows('SELECT point.*, version.id AS version_id, version.version_no, version.status AS version_status FROM drill_knowledge_points point INNER JOIN drill_knowledge_point_versions version ON version.knowledge_point_id = point.id ORDER BY point.id, version.version_no DESC'), 'resources' => $this->rows('SELECT resource.*, version.id AS version_id, version.version_code, version.status AS version_status FROM drill_learning_resources resource INNER JOIN drill_learning_resource_versions version ON version.learning_resource_id = resource.id ORDER BY resource.id, version.id DESC'), 'mappings' => $this->rows('SELECT * FROM drill_knowledge_mapping_versions ORDER BY id DESC'), 'content_gaps' => $this->rows("SELECT * FROM drill_content_gaps WHERE status = 'open' ORDER BY id DESC")]; }
    private function scope(array $context, array $staff): array { $role = function_exists('appRoleCode') ? appRoleCode((string) ($staff['role'] ?? '')) : strtolower((string) ($staff['role'] ?? '')); if (in_array($role, ['admin', 'operation'], true)) return ['scope_type' => 'all', 'staff_id' => (int) $context['staff_id'], 'store_ids' => []]; if ($role === 'manager') { $stmt = $this->pdo->prepare("SELECT DISTINCT store_id FROM staff_assignments WHERE staff_id = ? AND system_role = 'manager' AND start_date <= CURRENT_DATE AND (end_date IS NULL OR end_date >= CURRENT_DATE)"); $stmt->execute([(int) $context['staff_id']]); return ['scope_type' => 'stores', 'staff_id' => (int) $context['staff_id'], 'store_ids' => array_map('intval', $stmt->fetchAll(PDO::FETCH_COLUMN) ?: [])]; } return ['scope_type' => 'reviewer', 'staff_id' => (int) $context['staff_id'], 'store_ids' => []]; }
    private function scopeWhere(array $scope, string $assignmentAlias, string $taskAlias, array &$where, array &$params, ?string $ownerColumn = null, ?string $directStaffColumn = null): void { if ($scope['scope_type'] === 'all') return; if ($scope['scope_type'] === 'reviewer') { $where[] = $taskAlias . '.' . ($ownerColumn ?? 'reviewer_staff_id') . ' = ?'; $params[] = $scope['staff_id']; return; } if ($scope['store_ids'] === []) { $where[] = '1 = 0'; return; } $where[] = $assignmentAlias . '.staff_id IN (SELECT staff_id FROM staff_assignments WHERE store_id IN (' . implode(',', array_fill(0, count($scope['store_ids']), '?')) . ') AND start_date <= CURRENT_DATE AND (end_date IS NULL OR end_date >= CURRENT_DATE))'; array_push($params, ...$scope['store_ids']); }
    private function assertReviewScope(int $id, array $context, array $staff): void { if ($this->reviewRows($context, $staff, ['id' => $id]) === []) throw new DrillAdminScopeDeniedException('复核任务不在当前数据范围内。'); }
    private function assertCoachingScope(int $id, array $context, array $staff): void { if ($this->coachingRows($context, $staff, ['id' => $id]) === []) throw new DrillAdminScopeDeniedException('辅导任务不在当前数据范围内。'); }
    private function rows(string $sql, array $params = []): array { $stmt = $this->pdo->prepare($sql); $stmt->execute($params); return $stmt->fetchAll(PDO::FETCH_ASSOC) ?: []; }
    private function audit(int $actor, string $action, string $type, int $id, array $before, array $after): void { $stmt = $this->pdo->prepare('INSERT INTO drill_audit_logs (request_id, actor_staff_id, action, object_type, object_id, before_snapshot_json, after_snapshot_json, context_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'); $stmt->execute([function_exists('appRequestId') ? appRequestId() : null, $actor, $action, $type, $id, $this->json($before), $this->json($after), $this->json(['surface' => 'admin_drill_v2'])]); }
    private function json(array $value): string { return json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR); }
}
